name: Snyk Security Test

on:
  pull_request:
    branches: ['main']

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install project dependencies
        run: npm ci

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk tests
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
