name: Snyk Security
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      - name: Snyk Code test
        id: snyk-code-test
        run: |
          snyk code test --sarif > snyk-code.sarif || exit 0 # Ignore error and continue execution
          export SNYK_EXIT_CODE=$?
          if [ $SNYK_EXIT_CODE -ne 0 ]; then
            echo "Snyk Code test failed with exit code $SNYK_EXIT_CODE."
            echo "Error details:"
            cat snyk-code.sarif
            exit $SNYK_EXIT_CODE
          fi
      - name: Upload result to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
